### PR TITLE
GitHub enterprise support 

### PR DESCRIPTION
**Pull request by billimek**
This includes the requested changes for #12 

Adds support for using github enterprise or other github installations other than github.com where a valid github API is available.  This can be used via setting `$TRACKSUIT_GITHUB_API_URL` or command-line switch `--github-api-url=`

Also,
* Fixes typo in repositories description tag in main.go
* Adds additional check to filter out an empty `$TRACKSUIT_GITHUB_REPOSITORIES` variable so synchronization will continue on all repos in the org

### CODE REVIEW

**Comment by billimek** [comment]
FYI, @vito ^^^^^

**Comment by vito** [comment]
sorry to be a stickler but would you mind squashing and committing with a more descriptive message? e.g. "add support for github enterprise"

git history is important! :)

**Comment by billimek** [comment]
And done!

**Comment by billimek** [comment]
And done again! ^^ @vito

**Comment by vito** [comment]
thanks!

**Pull request merged**
