### PR TITLE
Enterprise GitHub

### LINKED ISSUE #4: Use tracksuit with enterprise github
The go-github lib is assuming we're only interested in using api.github.com.  However if we have an on-prem version of github, we should be able to indicate as such.  It looks like the go-github Client.BaseURL may be an avenue to set this, but I'm not sure (see https://github.com/google/go-github/blob/master/github/github.go#L68)

Is it possible to override these values to enable support for on-prem versions of github?

### PR DESCRIPTION
**Pull request by billimek**
Fixes #4

### CODE REVIEW

**Comment by bonzofenix** [comment]
@vito will this be merged?

Thanks!

**Comment by bonzofenix** [comment]
@vito ?

**Comment by billimek** [comment]
FYI I'm going to resubmit this PR with the changes @vito requested.  Waiting to do this work with someone else in a pair to help share knowledge.  Should be resubmitted sometime next week if all goes well

**Comment by billimek** [comment]
Closing due to #12

**Pull request closed without merging**
